don't attempt to open a web browser for the...
eclipse/che-devfile-registry pull request #311
Opened 2020-12-02 18:47 UTC by nickboldt

don't attempt to open a web browser for the generated PR, since this is expected to be run headless as a Jenkins job / GH action

Change-Id: Ia9e5f5fa7483c309765bb3cbd172568a0772d8c0
Signed-off-by: nickboldt <nboldt@redhat.com>

2020-12-02 19:00 UTC, JPinkney approved these changes

2020-12-02 19:33 UTC, benoitf requested changes
we have a PR template for more than one month but you're still not using it
Please use these templates
Thanks

2020-12-02 20:20 UTC, nickboldt commented
That's because I generate my PRs w/o using UI & button clickery, so I don't benefit from .github folder goodies. 

Anyway I've updated my PR gen script to apply the template.

2020-12-10 17:28 UTC, ericwill approved these changes

2020-12-10 17:29 UTC, merged